# Generated by Django 3.2.4 on 2021-07-16 14:20

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], default='M', max_length=10)),
                ('simage', models.ImageField(default='logo.png', upload_to='StudentImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], default='M', max_length=10)),
                ('timage', models.ImageField(default='logo.png', upload_to='TeacherImages/')),
                ('standard', models.CharField(choices=[('DF', 'selectClass'), ('class1', 'Class1'), ('class2', 'Class2'), ('class3', 'Class3')], default='DF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student')])),
                ('uid', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('DF', 'selectClass'), ('term1', 'Term1'), ('term2', 'Term2'), ('term3', 'Term3')], default='DF', max_length=10)),
                ('english', models.IntegerField(default=0)),
                ('telugu', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('science', models.IntegerField(default=0)),
                ('social', models.IntegerField(default=0)),
                ('said', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.teacher'),
        ),
        migrations.CreateModel(
            name='AttendanceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attpresent', models.IntegerField(default=0)),
                ('attabsent', models.IntegerField(default=0)),
                ('said', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentdates', models.DateField(default='2021-01-01')),
                ('said', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.student')),
            ],
        ),
    ]
