# Generated by Django 3.2.4 on 2021-07-19 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smail', models.EmailField(max_length=30)),
                ('rmail', models.EmailField(max_length=30)),
                ('sub', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sid', models.CharField(max_length=10)),
                ('tid', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='term',
            field=models.CharField(choices=[('DF', 'select Term'), ('term1', 'Term1'), ('term2', 'Term2'), ('term3', 'Term3')], default='DF', max_length=10),
        ),
    ]
